### ISSUE TITLE
GLIBC version too new for ubuntu 18

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#117]
Ubuntu 18 has GLIBC 2.27, and it is dangerous to upgrade glibc...

```
ldd --version
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

But it seems that perfetto need glibc 2.28+ 

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by trace_processor_shell-linux-0abc190c11cfdec87161dfad2716468016e6d534)
trace_processor_shell-linux-0abc190c11cfdec87161dfad2716468016e6d534: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by trace_processor_shell-linux-0abc190c11cfdec87161dfad2716468016e6d534)
trace_processor_shell-linux-0abc190c11cfdec87161dfad2716468016e6d534: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by trace_processor_shell-linux-0abc190c11cfdec87161dfad2716468016e6d534)

Traceback (most recent call last):
  File "entry.py", line 57, in <module>
    sys.exit(main())
  File "entry.py", line 46, in main
    result = SingleTraceProcessor(parsed_argv.traceFile).process()
  File "SingleTraceProcessor.py", line 24, in process
    file_path=self.trace_file)
  File "/usr/local/lib/python3.6/dist-packages/perfetto/trace_processor/api.py", line 176, in __init__
    bin_path=bin_path, unique_port=unique_port)
  File "/usr/local/lib/python3.6/dist-packages/perfetto/trace_processor/shell.py", line 35, in load_shell
    "Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug"
Exception: Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory
```

Can perfetto use lower version of glibc? or is there any older version of perfetto that use glibc 2.27?

**Comment by Kyson** [comment]
@primiano Can perfetto support cross build? i am building linux trace processor shell on my mac

gn build args

![image](https://user-images.githubusercontent.com/3901140/113296645-52af5b00-932c-11eb-9a62-3f922263ca5d.png)

but it build failed

![image](https://user-images.githubusercontent.com/3901140/113296549-31e70580-932c-11eb-8c2e-05791fc08ac8.png)

**Comment by primiano** [comment]
You cannot build from mac for Linux.

The only supported cross configurations supported are:
Target: Android, Host: Linux
Target: Android, Host: Mac
Target: Linux {arm, arm64, x86}, Host: Linux x86_64 (clang and gcx toolchains)

**Comment by Kyson** [comment]
Got it, thx

**Comment by gaogaotiantian** [comment]
Is there a way to workaround ``traceconv`` at this point for this issue?

**Comment by primiano** [comment]
Same as the above, rebuild it

**Comment by dc3671** [comment]
@primiano How to use the built one rather than the downloaded one when using python API `TraceProcessor`? Thanks~

**Comment by primiano** [comment]
@LalitMaganti knows better.
I think the way to go is using the bin_path argument to pass a custom path:

From src/trace_processor/python/example.py

`tp = TraceProcessor(file_path=args.file, bin_path=args.binary)`
