### ISSUE TITLE
Report issue when open trace file, and could not continue

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#218]
In stable version, it report the same issue, but result could be shown, in v21.0-9e3a964c5  version, it report following error, and shown is stopped:

```log
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

TypeError: Failed to construct 'Headers': String contains non ISO-8859-1 code point.
TypeError: Failed to construct 'Headers': String contains non ISO-8859-1 code point.
    at Object.<anonymous> (https://ui.perfetto.dev/v21.0-9e3a964c5/frontend_bundle.js:86503:25)
    at Generator.next (<anonymous>)
    at fulfilled (https://ui.perfetto.dev/v21.0-9e3a964c5/frontend_bundle.js:5611:62)

v21.0-9e3a964c5 9e3a964c585f3108b1ba2a1b58d4bb6ab96dc1ba
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
```

**Comment by LalitMaganti** [comment]
Are you using large trace mode https://perfetto.dev/docs/visualization/large-traces?

**Comment by soolaugust** [comment]
Current version is not reproduce,  close it as fixed
