### ISSUE TITLE
tools/heap_profile fails on ADT-3 with permission error trying to remove profile

### ISSUE THREAD

**Issue by tmm1** [google/perfetto#22]
```
Profiling active. Press Ctrl+C to terminate.
You may disconnect your device.

rm: /data/misc/perfetto-traces/profile-4abc119d-c8d4-402a-b8a8-b13262c1a260: Permission denied
Traceback (most recent call last):
  File "tools/heap_profile", line 479, in <module>
    sys.exit(main(sys.argv))
  File "tools/heap_profile", line 422, in main
    ['adb', 'shell', 'rm', PROFILE_DEVICE_PATH], stdout=NULL)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['adb', 'shell', 'rm', '/data/misc/perfetto-traces/profile-4abc119d-c8d4-402a-b8a8-b13262c1a260']' returned non-zero exit status 1.
```

**Comment by tmm1** [comment]
```
adt3:/ $ ls -alh /data/misc/perfetto-traces/
total 42K
drwxrwx-wx  2 root   shell 4.0K 2020-04-27 12:32 .
drwxrwx--t 45 system misc  4.0K 2020-04-27 12:14 ..
-rw-------  1 shell  shell    0 2020-04-27 12:32 profile-1eaaecd1-fe0d-4f62-b679-484cbfb7784f
-rw-------  1 shell  shell 6.0K 2020-04-27 12:33 profile-4abc119d-c8d4-402a-b8a8-b13262c1a260
-rw-------  1 shell  shell 7.4K 2020-04-27 12:33 profile-81bab641-b7c5-40a1-8499-fde17ef0a2d8
-rw-------  1 shell  shell 7.0K 2020-04-27 12:33 profile-8cce609c-cbb9-4498-b3fa-5f2e3c81a422
-rw-------  1 shell  shell 7.9K 2020-04-27 12:33 profile-bf76b874-d14a-40f4-8f5e-a869410abf41
-rw-------  1 shell  shell 9.1K 2020-04-27 12:33 profile-e0538cd2-aeec-4438-8b0b-826b752c9849
```

**Comment by tmm1** [comment]
Similarly I am unable to clean up the processes:

```
adt3:/ $ ps -e | grep perfet
shell        10547     1   38836   4164 SyS_epoll_wait      0 S perfetto
shell        10587     1   38836   4000 SyS_epoll_wait      0 S perfetto
shell        10610     1   38836   4008 SyS_epoll_wait      0 S perfetto
shell        10630     1   38836   3992 SyS_epoll_wait      0 S perfetto
shell        10659     1   38836   3912 SyS_epoll_wait      0 S perfetto
adt3:/ $ killall -KILL perfetto
killall: pid 10547: Permission denied
killall: pid 10587: Permission denied
killall: pid 10610: Permission denied
killall: pid 10630: Permission denied
killall: pid 10659: Permission denied
killall: perfetto: Permission denied
```

**Comment by segfaulthunter** [comment]
Thanks for the report.

Could you share your device fingerprint by running`adb shell getprop | grep fingerprint`?

Thanks!

**Comment by tmm1** [comment]
Sure!

```
[ro.bootimage.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
[ro.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
[ro.build.version.preview_sdk_fingerprint]: [REL]
[ro.odm.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
[ro.product.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
[ro.system.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
[ro.vendor.build.fingerprint]: [ADT-3/adt3/adt3:10/QTT1.200116.002.B6/6245789:user/release-keys]
```

I just received this device today. I am trying to hunt down some native memory leaks and would like to use heap_profiler on my app, and this seems to be one of the only Android 10 + Android TV available.

**Comment by segfaulthunter** [comment]
Fixed in https://r.android.com/1295382.

About the `killall`. You cannot KILL, but you can do TERM or INT instead. So just `killall perfetto` will do what you want.

Let me know if that works for you now.

**Comment by tmm1** [comment]
Thanks!

I copied the killall command from https://github.com/google/perfetto/blob/master/docs/heapprofd.md#concurrent-profiling-sessions

**Comment by segfaulthunter** [comment]
Can you confirm that this solved your problem? Thanks!

**Comment by tmm1** [comment]
Yep, I'm just trying it now and it seems to work as expected.

I also confirmed that regular `killall` works:

```
$ adb shell ps -e | grep perfetto
shell         7600     1   38836   3588 SyS_epoll_wait      0 S perfetto
$ adb shell killall perfetto
$ adb shell ps -e | grep perfett
$
```

Thanks a ton!
