### ISSUE TITLE
tools/heap_profile does not work with python3

### ISSUE THREAD

**Issue by tmm1** [google/perfetto#23]
```
Traceback (most recent call last):
  File "tools/heap_profile", line 436, in <module>
    sys.exit(main(sys.argv))
  File "tools/heap_profile", line 300, in main
    trace_to_text_binary = load_trace_to_text(platform)
  File "tools/heap_profile", line 66, in load_trace_to_text
    urllib.urlretrieve(url, local_file)
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

**Comment by tmm1** [comment]
```diff
diff --git a/tools/heap_profile b/tools/heap_profile
index 83887553a..7457c2d43 100755
--- a/tools/heap_profile
+++ b/tools/heap_profile
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3

 # Copyright (C) 2017 The Android Open Source Project
 #
@@ -28,7 +28,7 @@ import subprocess
 import sys
 import tempfile
 import time
-import urllib
+import urllib.request
 import uuid

 TRACE_TO_TEXT_SHAS = {
@@ -65,7 +65,7 @@ def load_trace_to_text(platform):
       return local_file

   url = TRACE_TO_TEXT_BASE_URL + file_name
-  urllib.urlretrieve(url, local_file)
+  urllib.request.urlretrieve(url, local_file)
   if not check_hash(local_file, sha_value):
     os.remove(local_file)
     raise ValueError("Invalid signature.")
```

**Comment by segfaulthunter** [comment]
Thanks. Fixed in https://r.android.com/1296596.

**Comment by segfaulthunter** [comment]
Also needs https://r.android.com/1295375, there was some str / byte problem as well. Thanks!
