### ISSUE TITLE
tools/diff_test_trace_processor.py meet permission problem

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#269]
but `out/android` is in same user with current user

```log
[==========] Running 1 tests.
[ RUN      ] cpu_frequency_limits.sql cpu_frequency_limits.textproto
Traceback (most recent call last):
  File "tools/diff_test_trace_processor.py", line 482, in <module>
    sys.exit(main())
  File "tools/diff_test_trace_processor.py", line 418, in main
    args.keep_input, args.rebase)
  File "tools/diff_test_trace_processor.py", line 215, in run_all_tests
    expected_path, tmp_perf_path)
  File "tools/diff_test_trace_processor.py", line 156, in run_query_test
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=ENV)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'out/android/'
```

**Comment by primiano** [comment]
Not sure how to help, there might be something weird in your setup. 
Are you using some bind mounts / docker or something else?
It works fine both on Linux and on Mac for me.

Also can you specify your full cmdline invocation and your environment (OS?  Distro? version of the codebase?)

**Comment by soolaugust** [comment]
I am using Ubuntu 18.04, and my codebase is today's newest version.

I worked on my host machine, not docker.

```log
Linux mi-HP-ProDesk-680-G6-PCI-Microtower-PC 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by LalitMaganti** [comment]
Are you running the script as follows:
```
tools/diff_test_trace_processor.py out/android/trace_processor_shell
```

Seems like you might be using
```
tools/diff_test_trace_processor.py out/android/
```
which is incorrect.
