### ISSUE TITLE
Shell is downloading invalid trace_processor_shell from http://get.perfetto.dev/trace_processor

### ISSUE THREAD

**Issue by mohamedmansour** [google/perfetto#338]
Today I realized the following bug:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from perfetto.trace_processor import TraceProcessor
>>> TraceProcessor(trace="C:\Temp\traces\traces\1.trace")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Edge\edgeinternal.es\TraceLab\.vpython\lib\site-packages\perfetto\trace_processor\api.py", line 255, in __init__
    self.http = self._create_tp_http(addr)
  File "C:\Edge\edgeinternal.es\TraceLab\.vpython\lib\site-packages\perfetto\trace_processor\api.py", line 321, in _create_tp_http
    url, self.subprocess = load_shell(self.config.bin_path,
  File "C:\Edge\edgeinternal.es\TraceLab\.vpython\lib\site-packages\perfetto\trace_processor\shell.py", line 53, in load_shell
    raise Exception(
Exception: Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug
```

Which is odd cause it worked the other month, so while debugging perfetto, it tries to download the trace_processor file from  http://get.perfetto.dev/trace_processor but it is just downloading 10KB meanwhile the original file is 6.7MB and it fails because the file is invalid, but the error is the wrong one.

Looking at this in lib\site-packages\perfetto\trace_processor\platform.py: It places the download in the folder:
```
   def get_shell_path(self, bin_path: str) -> str:
    if bin_path is not None:
      if not os.path.isfile(bin_path):
        raise Exception('Path to binary is not valid')
      return bin_path
    with tempfile.NamedTemporaryFile(delete=False) as file:
      req = request.Request(SHELL_URL)
      with request.urlopen(req) as req:
        file.write(req.read())
    if os.name != 'nt':
      subprocess.check_output(['chmod', '+x', file.name])
    return file.name
```

But in lib\site-packages\perfetto\trace_processor\shell.py: the value of shell_path doesn't have the exe. 
```
def load_shell(bin_path: str, unique_port: bool, verbose: bool,
               ingest_ftrace_in_raw: bool, platform_delegate: PlatformDelegate):
  addr, port = platform_delegate.get_bind_addr(
      port=0 if unique_port else TP_PORT)
  url = f'{addr}:{str(port)}'
  shell_path = platform_delegate.get_shell_path(bin_path=bin_path)
  if os.name == 'nt' and not shell_path.endswith('.exe'):
    tp_exec = [sys.executable, shell_path]
  else:
    tp_exec = [shell_path]
```
So when opening the port, it fails cause the file is invalid.
```
  p = subprocess.Popen(
      tp_exec + args,
      stdout=subprocess.DEVNULL,
      stderr=None if verbose else subprocess.DEVNULL)
```

The error is wrong because it assumes it is the unique_port issue, but it isn't. popen just failed to open the invalid file.
```
   while True:
    try:
      if p.poll() != None:
        if unique_port:
          raise Exception(
              "Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug"
          )
        raise Exception(
            "Trace processor failed to start, please file a bug at https://goto.google.com/perfetto-bug"
        )
      _ = request.urlretrieve(f'http://{url}/status')
      time.sleep(1)
      break
    except error.URLError:
      pass
```

I verified it because I already have the previous `trace_processor_shell.exe` downloaded and verified it works by doing:
```
        config = TraceProcessorConfig(
            bin_path="C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts\\trace_processor_shell.exe"
        )
        TraceProcessor(trace=trace_file, config=config).query(
            "select name,ts,dur from slice WHERE category = 'edge_hub_apps' ORDER BY ts;"
        )
```

**Comment by mohamedmansour** [comment]
@LalitMaganti I am on a physical box, and I don't get the message , `"no AVX2 available`, I had to do the following to get unblocked:

```
from perfetto.trace_processor import TraceProcessor
config = TraceProcessorConfig(
  bin_path="C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts\\trace_processor_shell.exe"
)
TraceProcessor(trace=trace_file, config=config).query(
  "select name,ts,dur from slice WHERE category = 'edge_hub_apps' ORDER BY ts;"
)
```

**Comment by LalitMaganti** [comment]
1) You don't need to be on a VM. Any pre-2015 machine will not have AVX2 and so will have the same problem.
2)
```
  bin_path="C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts\\trace_processor_shell.exe"
```
should not necessary if everything was working correctly.
3) The error message would not show up because as I mentioned, the version of the Python library containing the fixed error message has not been released.

**Comment by mohamedmansour** [comment]
@LalitMaganti my machine is from mid 2020 (chromium dev box), and it was working find few weeks ago with same version 0.5.0, and I am trying it now, and got `Exception: Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug` .

I assumed the 10KB script (didn't know what it did until you stated) but I have to explicitly place in `trace_processor_shell.exe` in the `bin_path` or it won't work. Did anything with windows update interfere with perfetto. 

Anything I can run locally to validate your theory about AVX2?

**Comment by LalitMaganti** [comment]
Can you run

**Comment by mohamedmansour** [comment]
@LalitMaganti  an update, I ran your command and it yielded:

```
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from perfetto.trace_processor import TraceProcessor, TraceProcessorConfig
>>> 
>>> TraceProcessor(trace="C:\Temp\perfetto\traces\1.trace", config=TraceProcessorConfig(verbose=True)) 
C:\Users\mmansour\AppData\Local\Temp\tmpceqe6ad5
['C:\\Edge\\edgeinternal.es\\perfetto\\.vpython\\Scripts\\python.exe', 'C:\\Users\\mmansour\\AppData\\Local\\Temp\\tmpceqe6ad5']
###################################################################################################################################################################### 100.0%
Traceback (most recent call last):
  File "C:\Users\mmansour\AppData\Local\Temp\tmpceqe6ad5", line 294, in <module>
    run_perfetto_prebuilt(TRACE_PROCESSOR_SHELL_MANIFEST)
  File "C:\Users\mmansour\AppData\Local\Temp\tmpceqe6ad5", line 286, in run_perfetto_prebuilt
    bin_path = get_perfetto_prebuilt(manifest)
  File "C:\Users\mmansour\AppData\Local\Temp\tmpceqe6ad5", line 279, in get_perfetto_prebuilt
    return download_or_get_cached(
  File "C:\Users\mmansour\AppData\Local\Temp\tmpceqe6ad5", line 250, in download_or_get_cached
    os.rename(tmp_path, bin_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts\\trace_processor_shell.exe.tmp' -> 'C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts\\trace_processor_shell.exe'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Edge\edgeinternal.es\perfetto\.vpython\lib\site-packages\perfetto\trace_processor\api.py", line 255, in __init__
    self.http = self._create_tp_http(addr)
  File "C:\Edge\edgeinternal.es\perfetto\.vpython\lib\site-packages\perfetto\trace_processor\api.py", line 321, in _create_tp_http
    url, self.subprocess = load_shell(self.config.bin_path,
  File "C:\Edge\edgeinternal.es\perfetto\.vpython\lib\site-packages\perfetto\trace_processor\shell.py", line 54, in load_shell
    raise Exception(
Exception: Random port allocation failed, please file a bug at https://goto.google.com/perfetto-bug
```
I deleted the folder: `C:\\Users\\mmansour\\.local\\share\\perfetto\\prebuilts` and it now works.

The `trace_processor_shell.exe.tmp` exists and perfetto attempts to write it and it fails. These were the files in that folder:
```
10/26/2022  05:07 PM         8,987,648 trace_processor_shell.exe
10/26/2022  05:07 PM                64 trace_processor_shell.exe.sha256
10/26/2022  05:06 PM         8,987,648 trace_processor_shell.exe.tmp
```

**Comment by LalitMaganti** [comment]
Above change should fix the issue with overwriting trace_processor_shell binary.
