### ISSUE TITLE
run ./heap_profile with error

### ISSUE THREAD

**Issue by eaggle** [google/perfetto#35]
^CTraceback (most recent call last):
  File "./heap_profile", line 495, in <module>
    sys.exit(main(sys.argv))
  File "./heap_profile", line 342, in main
    trace_to_text_binary = load_trace_to_text(platform)
  File "./heap_profile", line 68, in load_trace_to_text
    subprocess.check_call(['curl', '-L', '-#', '-o', local_file, url])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by primiano** [comment]
some more commentary would help.
What's not working? What were you ecpecting to happen?
What I see here is simply "you pressed ctrl-c" and that's the stacktrace

@segfaulthunter

**Comment by segfaulthunter** [comment]
It seems like you've interrupted `heap_profile` while it was downloading `trace_to_text`.

**Comment by eaggle** [comment]
curl: (7) Failed to connect to storage.googleapis.com port 443: Operation timed out

already resolved,thanks
