### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by zhaocc1106** [google/perfetto#379]
When i use the last version(v29.0-79101) to load tensorflow timeline profiler file. It reports the following error, but successful before. 

```
Oops, something went wrong. Please file a bug.
✕
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught Error: RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1368:14)
    at stackTrace (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1383:11)
    at abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1227:43)
    at _abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:4683:2)
    at Json::Value::asCString() const (wasm://wasm/01e98a8a:wasm-function[4226]:0x368e9c)
    at perfetto::trace_processor::JsonTraceParser::ParseJsonPacket(long long, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) (wasm://wasm/01e98a8a:wasm-function[4549]:0x38c47f)
    at perfetto::trace_processor::TraceSorter::ParseTracePacket(perfetto::trace_processor::TraceSorter::TimestampedDescriptor const&) (wasm://wasm/01e98a8a:wasm-function[1938]:0x1a271a)
    at perfetto::trace_processor::TraceSorter::SortAndExtractEventsUntilPacket(unsigned long long) (wasm://wasm/01e98a8a:wasm-function[1936]:0x1a1ced)
    at perfetto::trace_processor::TraceSorter::ExtractEventsForced() (wasm://wasm/01e98a8a:wasm-function[1923]:0x19f41c)
    at perfetto::trace_processor::TraceProcessorStorageImpl::Flush() (wasm://wasm/01e98a8a:wasm-function[1922]:0x19f3c8)
RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1368:14)
    at stackTrace (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1383:11)
    at abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1227:43)
    at _abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:4683:2)
    at Json::Value::asCString() const (wasm://wasm/01e98a8a:wasm-function[4226]:0x368e9c)
    at perfetto::trace_processor::JsonTraceParser::ParseJsonPacket(long long, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) (wasm://wasm/01e98a8a:wasm-function[4549]:0x38c47f)
    at perfetto::trace_processor::TraceSorter::ParseTracePacket(perfetto::trace_processor::TraceSorter::TimestampedDescriptor const&) (wasm://wasm/01e98a8a:wasm-function[1938]:0x1a271a)
    at perfetto::trace_processor::TraceSorter::SortAndExtractEventsUntilPacket(unsigned long long) (wasm://wasm/01e98a8a:wasm-function[1936]:0x1a1ced)
    at perfetto::trace_processor::TraceSorter::ExtractEventsForced() (wasm://wasm/01e98a8a:wasm-function[1923]:0x19f41c)
    at perfetto::trace_processor::TraceProcessorStorageImpl::Flush() (wasm://wasm/01e98a8a:wasm-function[1922]:0x19f3c8)
    at abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:1229:10)
    at _abort (https://ui.perfetto.dev/v29.0-791019539/engine_bundle.js:4683:2)
    at Json::Value::asCString() const (wasm://wasm/01e98a8a:wasm-function[4226]:0x368e9c)
    at perfetto::trace_processor::JsonTraceParser::ParseJsonPacket(long long, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) (wasm://wasm/01e98a8a:wasm-function[4549]:0x38c47f)
    at perfetto::trace_processor::TraceSorter::ParseTracePacket(perfetto::trace_processor::TraceSorter::TimestampedDescriptor const&) (wasm://wasm/01e98a8a:wasm-function[1938]:0x1a271a)
    at perfetto::trace_processor::TraceSorter::SortAndExtractEventsUntilPacket(unsigned long long) (wasm://wasm/01e98a8a:wasm-function[1936]:0x1a1ced)
    at perfetto::trace_processor::TraceSorter::ExtractEventsForced() (wasm://wasm/01e98a8a:wasm-function[1923]:0x19f41c)
    at perfetto::trace_processor::TraceProcessorStorageImpl::Flush() (wasm://wasm/01e98a8a:wasm-function[1922]:0x19f3c8)
    at perfetto::trace_processor::TraceProcessorImpl::Flush() (wasm://wasm/01e98a8a:wasm-function[197]:0x1ac6f)
    at perfetto::trace_processor::TraceProcessorImpl::NotifyEndOfFile() (wasm://wasm/01e98a8a:wasm-function[199]:0x1adf2)

stderr: 
undefined

v29.0-791019539 79101953901af770103b161100a1a3de1b47dfb3
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
```

**Comment by chromy** [comment]
Yep sorry, this is a know issue which should be fixed at HEAD.
You can use the autopush version of the UI while we sort out the roll.
These are the instructions for switching channels: https://perfetto.dev/docs/visualization/perfetto-ui-release-process#changing-release-channel
Internally this issues is tracked at b/256048719

**Comment by zhaocc1106** [comment]
> 256048719

Thanks

**Comment by chromy** [comment]
The stable UI has rolled an I can no longer reproduce this so hopefully it's fixed :)
