### ISSUE TITLE
Compilation error Ubuntu 22.04.1

### ISSUE THREAD

**Issue by andredasilvapinto** [google/perfetto#397]
I am getting this error when trying to build perfetto in a Ubuntu 22.04.1 VM:

```
$ tools/ninja -C out/linux tracebox traced traced_probes perfetto
ninja: Entering directory `out/linux'
[386/1131] ACTION //protos/perfetto/config:descriptor(//gn/standalone/toolchain:gcc_like)
FAILED: gen/protos/perfetto/config/config.descriptor
python3 ../../gn/standalone/protoc.py ./protoc --proto_path ../../ --include_imports --descriptor_set_out gen/protos/perfetto/config/config.descriptor --dependency_out gen/protos/perfetto/config/config.descriptor.d ../../protos/perfetto/config/trace_config.proto
Traceback (most recent call last):
  File "/home/andre/perfetto/out/linux/../../gn/standalone/protoc.py", line 60, in <module>
    sys.exit(main())
  File "/home/andre/perfetto/out/linux/../../gn/standalone/protoc.py", line 45, in main
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./protoc', '--descriptor_set_out', 'gen/protos/perfetto/config/config.descriptor', '--dependency_out', '/tmp/395068cd-20e7-4598-889c-e6652bb107cd', '--proto_path', '../../', '--include_imports', '../../protos/perfetto/config/trace_config.proto']' died with <Signals.SIGILL: 4>.
[388/1131] compile ../../src/base/event_fd.cc
ninja: build stopped: subcommand failed.
```

**Comment by primiano** [comment]
heya, is there any other log above?
this might be related with the AVX/SSE4 optimizations we assume.
Try building with `enable_perfetto_x64_cpu_opt = false` in GN args.

**Comment by andredasilvapinto** [comment]
Yes, that build arg solved it. Thanks
