### ISSUE TITLE
install-build-deps dies with stack-trace if curl is not installed

### ISSUE THREAD

**Issue by fergald** [google/perfetto#494]
It would be nice if it just said "you need to install curl" instead of dumping the stack below. That said, why does it even need curl? Why is it not fetching with python?

```
$@ tools/install-build-deps
...
INFO:root:Downloading /home/fergal/perfetto/buildtools/libbacktrace.zip from https://storage.googleapis.com/perfetto/libbacktrace-177940370e4a6b2509e92a0aaa9749184e64af43.zip
Traceback (most recent call last):
  File "/home/fergal/perfetto/tools/install-build-deps", line 699, in <module>
    sys.exit(Main())
             ^^^^^^
  File "/home/fergal/perfetto/tools/install-build-deps", line 616, in Main
    DownloadURL(dep.source_url, download_path)
  File "/home/fergal/perfetto/tools/install-build-deps", line 403, in DownloadURL
    subprocess.check_call(['curl', '-L', '-#', '-o', out_file, url])
  File "/usr/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'curl'
```

**Comment by LalitMaganti** [comment]
Given that:
a) curl is a very foundational piece of software
b) this is in a script used for building Perfetto and not for using it
fixing this is probably not the highest priority. Patches for this are welcome but not something we will likely get to ourselves.

As for why we use curl: you get nice progress bar, error information if stuff goes wrong etc. Yes we could write all that ourselves but again this is a development script, not something end users need to use.
