### ISSUE TITLE
[ui] Crash when page width is < 480 pixels wide

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#509]
I've observed a crash when the UI is loaded with a window width of < 480 pixels. This may not be a major issue, since Chome will not allow you to do this under normal conditions but it will sometimes happen when the Perfetto UI is loaded alongside chrome devtools since, devtools pane may be expanded horizontally

## how to reproduce

1. `./tools/open_trace_in_ui -i test/data/android_sched_and_ps.pb` to open a trace in Chrome
2. Press F12 to open chrome devtools
3. Click and drag the devtools pane until page width is < 480 pixels wide
4. Refresh the page

![image](https://github.com/google/perfetto/assets/77857237/97f75317-a4ae-48ee-8318-25f654095f53)

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught Error: PxSpan start > end
Error: PxSpan start > end
    at assertTrue (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:3253:16)
    at new PxSpan (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:8999:35)
    at OverviewTimelinePanel.onupdate (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:320151:25)
    at OverviewTimelinePanel.oncreate (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:320158:15)
    at Function.callHook (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:4654:17)
    at Function.render (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:5599:52)
    at globals_1.globals.rafScheduler.domRedraw [as _syncDomRedraw] (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:322878:28)
    at RafScheduler.syncDomRedraw (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:9504:15)
    at https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:9547:23
    at measure (https://ui.perfetto.dev/v34.0-15c2873e7/frontend_bundle.js:9329:7)

v34.0-15c2873e7 15c2873e764feb19949529074d67e2902fb30e57
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
```

**Comment by stevegolton** [comment]
Thanks for the bug report. Should be fixed in https://r.android.com/2615451
