### ISSUE TITLE
Opening test/data/compact_sched.pb causes UI to error

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#518]
Observed a error on ui.perfetto.dev (both stable & auto-push channels) when opening the test/data/compact_sched.pb.

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Error: Error @ row: 7 col: 'lastSliceId': SQL value is NULL but that was not expected (expected type: NUM). Did you mean NUM_NULL, LONG_NULL, STR_NULL or BLOB_NULL?
Error: Error @ row: 7 col: 'lastSliceId': SQL value is NULL but that was not expected (expected type: NUM). Did you mean NUM_NULL, LONG_NULL, STR_NULL or BLOB_NULL?
    at RowIteratorImpl.tryMoveToNextBatch (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:4068:25)
    at RowIteratorImpl.next (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:3958:25)
    at new RowIteratorImpl (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:3928:16)
    at new RowIteratorImplWithRowData (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:4084:24)
    at QueryResultImpl.firstRow (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:3668:24)
    at CpuSliceTrackController.onSetup (https://ui.perfetto.dev/v34.0-1b8de4452/frontend_bundle.js:282536:43)

v34.0-1b8de4452 1b8de44522f33d371def110325bf31b847c1f5c4
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
```

After dismissing the error, the CPU 4 track appears to be stuck loading:
![image](https://github.com/google/perfetto/assets/77857237/b88d462f-f5f2-4aa1-9368-02da90b3cea2)

# How to reproduce:

1. clone the repo
2. `./tools/install-build-deps` (to populate the test/data directory)
3. `./tools/open_trace_in_ui -i test/data/compact_sched.pb`
4. Error should be immediately visible upon load.

**Comment by chromy** [comment]
Thanks! https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2639792 for this.
