### ISSUE TITLE
Error "No route to host"  when i run python api to query sql data 

### ISSUE THREAD

**Issue by jusReal** [google/perfetto#548]
from perfetto.trace_processor import TraceProcessor
    
    if __name__ == '__main__':
        # Initialise TraceProcessor with a trace file
        tp = TraceProcessor(addr='localhost:9001')
        tp.query("select * from thread where id = 0")

-----

    ╰─ ./trace_processor out_release.pb --httpd              ─╯
    [240.927] processor_shell.cc:1641 Trace loaded: 716.10 MB in 33.94s (21.1 MB/s)
    Error stats for this trace:
                                        name                                      idx                                   source                                    value
    ---------------------------------------- ---------------------------------------- ---------------------------------------- ----------------------------------------
    ftrace_cpu_overrun_delta                                                        7 trace                                                                       17065
    [240.927]             httpd.cc:99 [HTTP] Starting RPC server on localhost:9001
    [240.927]            httpd.cc:104 [HTTP] This server can be used by reloading https://ui.perfetto.dev and clicking on YES on the "Trace Processor native acceleration" dialog or through the Python API (see https://perfetto.dev/docs/analysis/trace-processor#python-api).
    [241.301]       http_server.cc:83 [HTTP] New connection
    [241.301]       http_server.cc:83 [HTTP] New connection
    [241.307]      http_server.cc:231 [HTTP] GET / [body=0B, origin=""]

-----

    Traceback (most recent call last):
      File "/Users/pythonProjects/devops-scripts/startup_opt/stat_thread.py", line 6, in <module>
        tp.query("select * from thread where id = 0")
      File "/usr/local/lib/python3.9/site-packages/perfetto/trace_processor/api.py", line 282, in query
        response = self.http.execute_query(sql)
      File "/usr/local/lib/python3.9/site-packages/perfetto/trace_processor/http.py", line 32, in execute_query
        self.conn.request('POST', '/query', body=byte_data)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
        self.send(msg)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
        self.connect()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 921, in connect
        self.sock = self._create_connection(
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 843, in create_connection
        raise err
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 831, in create_connection
        sock.connect(sa)
    OSError: [Errno 65] No route to host

**Comment by LalitMaganti** [comment]
The address should be `'http://localhost:9001'` not `'localhost:9001'`
