### ISSUE TITLE
Support uploading files with ISO-8559-1 characters

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#577]
Hi, I tried to upload a json trace file with a file name containing non ascii characters on `ui.perfetto.dev` and it crashed:

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

TypeError: Failed to construct 'Headers': String contains non ISO-8859-1 code point.
TypeError: Failed to construct 'Headers': String contains non ISO-8859-1 code point.
    at cacheTrace (https://ui.perfetto.dev/v35.0-8019b8809/frontend_bundle.js:312215:22)
    at async TraceController.cacheCurrentTrace (https://ui.perfetto.dev/v35.0-8019b8809/frontend_bundle.js:318236:16)
    at async TraceController.loadTrace (https://ui.perfetto.dev/v35.0-8019b8809/frontend_bundle.js:317938:28)

v35.0-8019b8809 8019b8809dfbec51c8e1ca38e83c8b60da626585
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
```

You can use ``测试.json`` as the file name and it should trigger the issue. It would be nice if Perfetto can support files with characters other than ascii.

Thanks!

**Comment by LalitMaganti** [comment]
Fixed by https://r.android.com/2831350
