### ISSUE TITLE
[UI] crash when navigating to any page on sidebar

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#604]
Autopush UI appears to crash when navigating to any of the pages in the sidebar after loading a trace.

Current UI version as of this issue appears to be: https://android.googlesource.com/platform/external/perfetto/+/3306717b72d2d1dfd8f1958a9dcc735c3dd65c27/ui

<img width="1649" alt="image" src="https://github.com/google/perfetto/assets/77857237/7ca68532-3905-46c0-92e0-eaf1e4343aa6">

# How to reproduce:
1. open perfetto ui
2. click on "Open Android Example"
3. click on one of: "Viz", "Query (SQL)", "Metrics", or "info and metadata"
4. observe error

Error message:
```
Trace: https://storage.googleapis.com/perfetto-misc/example_android_trace_15s

Viewed on: https://ui.perfetto.dev

Query: drop table window_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf; drop table span_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf
Error: Traceback (most recent call last):
  File "stdin" line 1 col 1
    drop table window_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf
    ^
no such table: window_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf
Error: Traceback (most recent call last):
  File "stdin" line 1 col 1
    drop table window_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf
    ^
no such table: window_c3b8ca6c_8a48_4919_b4e3_14debd5f00cf
    at QueryResultImpl.resolveOrReject (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:302180:30)
    at QueryResultImpl.appendResultBatch (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:302166:20)
    at WaitableQueryResultImpl.appendResultBatch (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:302529:28)
    at WasmEngineProxy.onRpcResponseMessage (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:302732:31)
    at WasmEngineProxy.onRpcResponseBytes (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:302663:19)
    at WasmEngineProxy.onMessage (https://ui.perfetto.dev/v37.0-3306717b7/frontend_bundle.js:323854:16)

v37.0-3306717b7 3306717b72d2d1dfd8f1958a9dcc735c3dd65c27
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
```

**Comment by chromy** [comment]
Thanks for reporting! I can confirm we can reproduce this on `autopush`. Please use the `canary` or `stable` channels while we work on a fix.
